xcursorgen in tetris/cursors/left_ptr
xcursorgen in tetris/cursors/arrow
xcursorgen in tetris/cursors/based_arrow_up
xcursorgen in tetris/cursors/bd_double_arrow
xcursorgen in tetris/cursors/bottom_left_corner
xcursorgen in tetris/cursors/bottom_right_corner
xcursorgen in tetris/cursors/bottom_side
xcursorgen in tetris/cursors/circle
xcursorgen in tetris/cursors/copy
xcursorgen in tetris/cursors/crossed_circle
xcursorgen in tetris/cursors/crosshair
xcursorgen in tetris/cursors/double_arrow
xcursorgen in tetris/cursors/draft_large
xcursorgen in tetris/cursors/draft_small
xcursorgen in tetris/cursors/fd_double_arrow
xcursorgen in tetris/cursors/fleur
xcursorgen in tetris/cursors/h_double_arrow
xcursorgen in tetris/cursors/hand
xcursorgen in tetris/cursors/hand1
xcursorgen in tetris/cursors/hand2
xcursorgen in tetris/cursors/left_ptr_watch
xcursorgen in tetris/cursors/left_side
xcursorgen in tetris/cursors/link
xcursorgen in tetris/cursors/question_arrow
xcursorgen in tetris/cursors/right_ptr
xcursorgen in tetris/cursors/right_side
xcursorgen in tetris/cursors/sb_down_arrow
xcursorgen in tetris/cursors/sb_h_double_arrow
xcursorgen in tetris/cursors/sb_left_arrow
xcursorgen in tetris/cursors/sb_right_arrow
xcursorgen in tetris/cursors/sb_up_arrow
xcursorgen in tetris/cursors/sb_v_double_arrow
xcursorgen in tetris/cursors/top_left_arrow
xcursorgen in tetris/cursors/top_left_corner
xcursorgen in tetris/cursors/top_right_corner
xcursorgen in tetris/cursors/top_side
xcursorgen in tetris/cursors/v_double_arrow
xcursorgen in tetris/cursors/watch
xcursorgen in tetris/cursors/X_cursor
xcursorgen in tetris/cursors/xterm
